# Generated by Django 4.1.6 on 2023-02-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=384, null=True),
        ),
    ]
